<?php echo $this->doctype(); ?>
<html lang="en" ng-app="">
    <head>
        <meta charset="utf-8">
        <title>Zf2 Angular</title>
        <script src="/js/angular.min.js"></script>
    </head>
    <body>
        <div ng-controller="CtrlApp">
            <input type="text" ng-model="nome">
            <h1>{{nome}}</h1>
        </div>
        <script>
           var CtrlApp = function($scope){
               $scope.nome = "Marcio";
           }
        </script>
    </body>
</html>
