<?php echo $this->doctype(); ?>
<html lang="en" ng-app="myApp">
    <head>
        <meta charset="utf-8">
        <title>Zf2 Angular</title>
        <link href="/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
    </head>
    <body>
        <!-- Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/#/">ZF2 AngularJs</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="/#/categorias">Categorias</a></li>
                        <li><a href="/#/produtos">Produtos</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <?php echo $this->content; ?>
        <script src="/js/angular.min.js"></script>
        <script src="/js/angular-route.min.js"></script>
        <script src="/js/angular-resource.min.js"></script>
        <script src="/projetoangular/app.js"></script>
        <script src="/projetoangular/controllers.js"></script>
        <script src="/projetoangular/services.js"></script>
    </body>
</html>
