<?php echo $this->doctype(); ?>
<html lang="en" ng-app="Categorias">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Zf2 Angular</title>
        <link href="/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Zf2 Angular</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Produtos</a></li>
                    <li><a href="#about">Categorias</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
        <div class="container">

            <div class="starter-template" ng-controller="CategoriasCtrl">
                <h1>Conteúdo</h1>
                <p class="lead">{{nome}}</p>
            </div>

        </div><!-- /.container -->
        <script src="/js/angular.min.js"></script>
        <script src="/js/projetoangular/Categorias.js"></script>
        <script src="/js/projetoangular/CategoriasCtrl.js"></script>
    </body>
</html>
